name: SpitPlugin
version: 1.0
main: hex.wald.spitplugin.SpitPlugin
api-version: 1.20

commands:
  spit:
    description: Spit command
    usage: /spit
  spitmenu:
    description: Spit menu command
    usage: /spitmenu

permissions:
  spit.use:
    default: true
